



def extract_puzzle(puzzle: str):
    """
    This function takes a puzzle generated by chatgpt and removes all the trash chatgpt created,
    i.e:
    - everyting except the code (outside ``` marks)
    - comments from the code
    """
    if not puzzle.find("```") == -1:
        puzzle = puzzle.split("```")[1]

    if not puzzle.find("#") == -1:
        puzzle = remove_comments(puzzle)

    return puzzle

def remove_comments(string: str):
    isInComment=False
    returnVal = ""
    for char in string:
        if char == '#':
            isInComment = True
        elif char == "\n":
            isInComment = False
        if not isInComment:
            returnVal += char
    return returnVal
